# Use root/example as user/password credentials
version: '3'

volumes:
  db_vol:

networks:
  produto_net:
    driver: bridge

services:
  mongodb:
    image: mongo:4.4.3
    ports:
    - 27017:27017
    networks:
     - produto_net
    volumes:
     - db_vol:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd