# Use root/example as user/password credentials
version: '3'

volumes:
  db_vol:

networks:
  produto_net:
    driver: bridge

services:
  mongo:
    image: mongo:4.4.3
    ports:
    - "0.0.0.0:27017:27017"
    networks:
     - produto_net
    volumes:
     - db_vol:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  mongo-express:
    image: mongo-express:latest
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongopwd
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - produto_net
    depends_on:
      - mongo

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    networks:
     - produto_net
    volumes:
     - db_vol:/data/mariadb

  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example   
    networks:
     - produto_net
    volumes:
     - db_vol:/data/postgresql
  
  redis-server:
    image: "redis:alpine"
    command: redis-server
    ports:
     - "6379:6379"
    networks:
     - produto_net
    volumes:
     - db_vol:/data/redis
    